/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Virtual Pandora (https://sketchfab.com/virtualpandora)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hoodie-97611a53e3b846f69e0655b210f72b2f
title: Hoodie
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { proxy,useSnapshot } from 'valtio'


export default function Model({straps,color,rib,props}) {
  const state=proxy({
    current:null,
    items:{
        straps:straps,
        body: color,
        rib:rib
        
       
    }
  })
  const group = useRef()
  const snap =useSnapshot(state)
  const { nodes, materials } = useGLTF('/hoodie.gltf')
  return (
    <group  scale={500}  ref={group} {...props} dispose={null} >
      <group  scale={0.02} position={[0,0, 0]} rotation={[-Math.PI / 2, 0, 0]}  >
        <mesh geometry={nodes.Object_2.geometry} material={materials.BTN_FABRIC_FRONT_1944972} />
        <mesh material-color={snap.items.body} geometry={nodes.Object_3.geometry} material={materials.Holes_FRONT_1944945} />
        <mesh material-color={snap.items.body} geometry={nodes.Object_4.geometry} material={materials.Knit_Fleece_Terry_FRONT_1944906} />
        <mesh material-color={snap.items.body} geometry={nodes.Object_5.geometry} material={materials.Knit_Fleece_Terry_FRONT_1944906} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Material125269} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Material2501413} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Material2501423} />
        <mesh material-color={snap.items.rib} geometry={nodes.Object_9.geometry} material={materials.Rib_wide_FRONT_1944924} />
        <mesh material-color={snap.items.straps} geometry={nodes.Object_10.geometry} material={materials.Straps_FRONT_1944954} />
      </group>
    </group>
  )
}

useGLTF.preload('/hoodie.gltf')
