/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ShirtCamera.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={100}>
            <mesh geometry={nodes['T-Shirt005_Shirt001_0'].geometry} material={materials['Shirt.001']} scale={0.16} />
            <mesh geometry={nodes['T-Shirt_Cuello'].geometry} material={materials.Extra} />
          </group>
        </group>
      </group>
      <PerspectiveCamera makeDefault={true} far={100} near={0.1} fov={20.6} position={[2.51, 7.16, 31.11]} rotation={[-0.11, 0.09, -0.01]} />
    </group>
  )
}

useGLTF.preload('/ShirtCamera.gltf')
