/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kodie Russell (https://sketchfab.com/KodieRussell)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dickies-long-sleeve-shirt-f6f27327fbaf423081ae9da8e5dc109e
title: Dickies Long Sleeve Shirt
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/shirt.gltf')
  return (
    <group ref={group} {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]}  >
        <group rotation={[Math.PI / 2, 0, 0]} >
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Shirt} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shirt.gltf')
