/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tshirtNew.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={100}>
            <mesh material-color={"#76eec6"} geometry={nodes['T-Shirt_Base'].geometry} material={materials.Primary} position={[-0.13, 0.28, -0.42]} scale={0.03} />
            <mesh geometry={nodes['T-Shirt_Orillas'].geometry} material={materials.Extra} position={[-0.13, 0.28, -0.42]} scale={0.03} />
            <mesh geometry={nodes['T-Shirt_Rayas'].geometry} material={materials.Secondary} position={[-0.13, 0.28, -0.42]} scale={0.03} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tshirtNew.gltf')